# coding: utf-8
import json

with open('mobile_app/tool/en_ja_ref.json', 'r', encoding='utf-8') as f:
    ref = json.load(f)

ko = {"@@locale": "ko"}

# 1. Direct mappings
direct = {
    "appName": "AstraCue",
    "analyticsConsentTitle": "이용 현황 분석 (선택)",
    "analyticsConsentBody": "AstraCue 서비스 품질 개선을 위해 Firebase 및 Google Analytics를 통한 이용 통계 수집을 허용합니다. 이름, 출생 정보, 개인 점술 내용은 일절 전송되지 않으며, '안전한 이용' 메뉴에서 언제든지 끌 수 있습니다.",
    "analyticsConsentSaveFailed": "설정을 저장하지 못했습니다. 이번 세션 동안 분석 기능이 꺼집니다.",
    "continueAction": "계속하기",
    "backAction": "뒤로",
    "closeAction": "닫기",
    "tryAgain": "다시 시도",
    "responsibleUse": "안전한 이용 안내",
    "history": "기록",
    "onboardingTitle": "우주의 신호와 당신의 직관에 귀 기울여 보세요.",
    "onboardingLanguageHint": "언어를 변경하려면 상단의 지구본 아이콘을 탭하세요.",
    "yourProfile": "나의 프로필",
    "signAfterBirthDate": "생년월일을 입력하면 별자리가 표시됩니다",
    "buildPattern": "나만의 고유한 에너지를 발견해 보세요.",
    "profileExplainer": "분석에 활용될 에너지 주기를 계산합니다.",
    "nameField": "이름",
    "dateOfBirth": "생년월일",
    "selectBirthDate": "생년월일 선택",
    "birthDateRequired": "계속하려면 생년월일을 선택해 주세요.",
    "birthDay": "일",
    "birthMonth": "월",
    "birthYear": "년",
    "birthDateScroll": "스크롤",
    "birthDateType": "직접 입력",
    "birthDateInvalid": "1900년부터 오늘 사이의 올바른 날짜를 입력해 주세요.",
    "birthTimeUnknown": "출생 시간 모름",
    "birthTimeUnknownDetail": "출생 시간을 모르는 경우, 당신의 성향과 가장 가까운 시간대를 바탕으로 계산합니다.",
    "timeOfBirth": "출생 시간",
    "countryOfBirth": "출생 국가",
    "selectBirthCountry": "국가 검색 및 선택",
    "birthCountryRequired": "계속하려면 출생 국가를 선택해 주세요.",
    "createCompass": "나의 나침반 만들기",
    "birthPrivacyPrototype": "이 체험 버전에서는 출생 정보가 외부에 공개되지 않고 안전하게 보호됩니다.",
    "homeEyebrow": "당신을 이끄는 마음의 나침반",
    "homeTitle": "선택 앞에서 망설이고 계신가요?",
    "areaQuestion": "어떤 분야에 대한 고민인가요?",
    "findDirection": "나아갈 방향 찾기",
    "todaySignals": "오늘의 신호",
    "dailyEnergy": "오늘의 에너지",
    "yourColorsToday": "오늘의 색상:",
    "luckyNumberToday": "오늘의 행운의 숫자:",
    "categoryOverall": "종합",
    "categoryLove": "사랑과 인연",
    "categoryCareer": "커리어",
    "categoryMoney": "재정",
    "categoryStudy": "배움과 성장",
    "categoryFriends": "친구",
    "categoryOther": "기타",
    "periodQuestion": "어느 시간대를 염두에 두고 계신가요?",
    "periodNow": "지금",
    "periodMorning": "아침",
    "periodMidday": "낮",
    "periodAfternoon": "오후",
    "periodEvening": "저녁",
    "periodPassed": "지남",
    "periodTooLittleTime": "지남",
    "periodCheckingTimezone": "시간대 확인 중",
    "periodHasPassed": "{period} 시간이 지났습니다. 다른 시간대를 선택해 주세요.",
    "periodNotEnoughTimeLeft": "오늘 {period} 시간이 얼마 남지 않았습니다. 다른 시간대를 선택해 주세요.",
    "periodPassedShort": "지남",
    "reveal": "분석하기",
    "aligning": "조율 중",
    "tapWhenReady": "준비가 되면 탭하세요",
    "keepChoiceInMind": "마음속에 고민을 선명히 떠올려 보세요.",
    "consultingPatterns": "오늘의 상징적 패턴을 읽어내는 중...",
    "readingSteadyMessage": "서두르지 마세요. 좋은 신호는 차분함 속에서 드러납니다.",
    "decisionBalance": "균형",
    "noClearLeaning": "오늘의 신호는 어느 한쪽으로 치우치지 않고 균형을 이루고 있습니다.",
    "insufficientData": "판단을 내리기에는 데이터가 충분하지 않습니다.",
    "lookAgainLater": "나중에 다시 흐름을 살펴보세요.",
    "saveReading": "결과 저장하기",
    "savedToHistory": "기록에 저장되었습니다",
    "shareInsight": "통찰 공유하기",
    "shareReadingCard": "점술 카드 공유",
    "timeWindowFormat": "{start} – {end}",
    "resultDisclaimerNote": "일상의 성찰을 돕는 참고용입니다. 전문적인 의료, 법률, 금융 자문을 대신하지 않습니다.",
    "choiceYes": "예",
    "choiceNo": "아니오",
    "choiceAct": "행동",
    "choiceWait": "기다림",
    "choiceAdvance": "전진",
    "choiceRetreat": "후퇴",
    "choiceStay": "유지",
    "choiceGo": "이동",
    "choiceKeep": "간직",
    "choiceLetGo": "비우기",
    "choiceCommit": "전념",
    "choiceWithdraw": "물러남",
    "choiceLeft": "왼쪽",
    "choiceRight": "오른쪽",
    "choiceForward": "앞으로",
    "choiceBackward": "뒤로",
    "luckiestTimesMorning": "오늘 아침 가장 상서로운 시간",
    "luckiestTimesMidday": "오늘 낮 가장 상서로운 시간",
    "luckiestTimesAfternoon": "오늘 오후 가장 상서로운 시간",
    "luckiestTimesEvening": "오늘 저녁 가장 상서로운 시간",
    "luckyTimesMorning": "아침의 상서로운 시간",
    "luckyTimesMidday": "낮의 상서로운 시간",
    "luckyTimesAfternoon": "오후의 상서로운 시간",
    "luckyTimesEvening": "저녁의 상서로운 시간",
    "luckyTimesCaveat": "상징적 지표이며 특정 사건을 보장하지 않습니다.",
    "colorRoleLead": "주요 색상",
    "colorRoleSupporting": "보조 색상",
    "colorToKeepNear": "가까이 두면 좋은 색상: {name}",
    "colorsToKeepNear": "가까이 두면 좋은 색상: {first}, {second}",
    "colorRoleSemantics": "{role} 색상, {name}",
    "colorRoleUnavailableSemantics": "{role} 색상을 아직 확인할 수 없습니다",
    "readingAreaSemantics": "점술 영역: {category}",
    "readingForCategory": "{category} 점술",
    "zodiacAvatarSemantics": "{sign} 별자리 아바타",
    "energyInsightNewTooltip": "오늘의 새로운 에너지 통찰",
    "energyInsightReadTooltip": "오늘의 에너지 통찰 읽기",
    "energyInsightHideTooltip": "오늘의 에너지 의미 숨기기",
    "energyInsightCoachMark": "매일 이곳에서 새로운 에너지 통찰을 만나보세요.",
    "ritualLocked": "선택의 순간이 정해졌습니다.",
    "errorNetworkHeadline": "연결 상태가 원활하지 않습니다.",
    "errorNetworkDetail": "네트워크 연결을 확인한 후 다시 시도해 주세요.",
    "errorServerHeadline": "지금은 점술을 완료할 수 없습니다.",
    "errorServerDetail": "일시적인 서비스 지연입니다. 잠시 후 다시 시도해 주세요.",
    "errorRejectedHeadline": "프로필 정보를 다시 확인해 주세요.",
    "errorRejectedDetail": "출생 정보를 검토한 후 새로운 점술을 시작해 주세요.",
    "errorInvalidHeadline": "결과를 불러올 수 없습니다.",
    "errorInvalidDetail": "앱을 최신 버전으로 업데이트하면 정상 이용하실 수 있습니다.",
    "errorConfigurationHeadline": "점술 서비스가 설정되지 않았습니다.",
    "errorConfigurationDetail": "앱 빌드 설정을 확인해 주세요.",
    "responsibleUseTitle": "안전하고 책임감 있는 이용 안내",
    "responsibleUseSubtitle": "AstraCue는 의사결정을 대신 내려주는 도구가 아닌, 일상을 돌아보는 성찰의 나침반입니다.",
    "boundaryEverydayTitle": "일상의 성찰을 위한 도구",
    "boundaryEverydayBody": "본 서비스는 일상의 작은 고민을 돌아보기 위한 상징적 가이드입니다. 의료, 법률, 전문 투자 등 중대한 결정은 공인된 전문가와 상의하세요.",
    "boundaryNotCommandTitle": "명령이 아닌 방향 제시",
    "boundaryNotCommandBody": "나침반은 방향을 비출 뿐 결정을 강요하지 않습니다. 모든 선택의 주체는 언제나 당신 자신입니다.",
    "boundaryCrisisTitle": "위기 상황 지원 안내",
    "boundaryCrisisBody": "극심한 고통이나 심리적 위기 상황에 처해 계시다면, 전문 상담 기관이나 긴급 지원 센터에 즉시 도움을 요청해 주세요.",
    "boundaryPrivacyTitle": "안전한 정보 보호",
    "boundaryPrivacyBody": "입력하신 생년월일과 시간 정보는 기기 내에서만 안전하게 처리되며 외부에 유출되지 않습니다.",
    "safetyUnderstood": "이해했습니다",
    "orbitBaZi": "사주팔자",
    "orbitZiWei": "자미두수",
    "orbitAlmanac": "역법",
    "orbitVedic": "베다 점성술",
    "orbitNumerology": "수비학",
    "orbitLunarPhase": "달의 위상",
    "orbitPlanetary": "행성 운행",
    "orbitYinYang": "음양의 조화",
    "orbitRhythm": "우주의 리듬",
    "orbitMoment": "시간의 기운",
    "orbitBalance": "조화와 균형",
    "dailyQuotaExhaustedTitle": "오늘 무료 점술 3회를 모두 사용했습니다",
    "energyCooldownTitle": "에너지 충전 중 ({countdown})",
    "editProfile": "프로필 수정",
    "profileUpdated": "프로필이 업데이트되었습니다.",
    "saveChanges": "변경사항 저장",
    "discardChanges": "변경사항 취소",
    "cancelAction": "취소",
    "profileSaved": "프로필이 저장되었습니다.",
    "profileBirthDateLocked": "{wait} 후에 생년월일을 다시 변경할 수 있습니다.",
    "profileBirthTimeLocked": "{wait} 후에 출생 시간을 다시 변경할 수 있습니다.",
    "profileBirthCountryLocked": "{wait} 후에 출생 국가를 다시 변경할 수 있습니다.",
    "profileWaitHoursMinutes": "{hours}시간 {minutes}분",
    "profileWaitMinutes": "{minutes}분",
    "profileConfirmBirthDate": "변경 후 4시간 동안 생년월일이 고정됩니다.",
    "profileConfirmBirthTime": "변경 후 2시간 동안 출생 시간이 고정됩니다.",
    "profileConfirmBirthCountry": "변경 후 1시간 동안 출생 국가가 고정됩니다.",
    "profileBirthTimeUnknownValue": "모름",
    "profileReadingsUnchanged": "기존에 저장된 점술 기록은 그대로 유지됩니다.",
    "defaultUserName": "여행자",
    "zodiacAries": "양자리",
    "zodiacTaurus": "황소자리",
    "zodiacGemini": "쌍둥이자리",
    "zodiacCancer": "게자리",
    "zodiacLeo": "사자자리",
    "zodiacVirgo": "처녀자리",
    "zodiacLibra": "천칭자리",
    "zodiacScorpio": "전갈자리",
    "zodiacSagittarius": "사수자리",
    "zodiacCapricorn": "염소자리",
    "zodiacAquarius": "물병자리",
    "zodiacPisces": "물고기자리",
    "energyLevelRadiant": "찬란함",
    "energyLevelSteady": "안정",
    "energyLevelRestless": "일렁임",
    "energyLevelFading": "여운",
    "energyLevelTurbulent": "소용돌이",
    "energyLevelStill": "고요",
    "energyLevelQuiet": "고요",
    "energyLevelSoft": "부드러움",
    "energyLevelFlowing": "유려함",
    "energyLevelFocused": "집중",
    "energyLevelLively": "활기",
    "energyLevelBright": "밝음",
    "colorAmberGold": "앰버 골드",
    "colorBronze": "브론즈",
    "colorCarmine": "카민 레드",
    "colorCharcoal": "차콜",
    "colorCinnabar": "주홍",
    "colorCopper": "코퍼",
    "colorCoralRed": "코랄 레드",
    "colorCrimson": "크림슨",
    "colorDeepPlum": "딥 플럼",
    "colorEmerald": "에메랄드",
    "colorIndigo": "인디고",
    "colorInkBlack": "먹빛",
    "colorIvory": "아이보리",
    "colorJade": "옥색",
    "colorLapis": "라피스 라줄리",
    "colorMidnightNavy": "미드나잇 네이비",
    "colorMoonlightSilver": "달빛 실버",
    "colorObsidian": "흑요석",
    "colorPearlWhite": "진주빛 화이트",
    "colorRoseGold": "로즈 골드",
    "colorSage": "세이지 그린",
    "colorSand": "모래빛",
    "colorSunYellow": "태양빛 옐로우",
    "colorWarmAmber": "따뜻한 호박색",
    "colorSilver": "실버",
    "colorOchre": "황토색",
    "colorCedar": "삼나무색",
    "colorEmber": "잉걸불색",
    "colorRose": "로즈",
    "colorPearl": "펄",
    "colorMint": "민트",
    "colorSteel": "스틸",
    "colorAzure": "애저 블루",
    "colorClay": "점토색",
    "colorSolarCoral": "솔라 코랄",
    "colorChampagne": "샴페인",
    "colorOceanBlue": "오션 블루",
    "colorBlossom": "꽃잎색",
    "colorMistBlue": "안개 블루",
    "colorAmber": "호박색",
    "selectBirthTime": "출생 시간 선택",
    "birthTimeRequired": "출생 시간을 선택해 주세요.",
    "knowBirthTime": "출생 시간을 알고 계신가요?",
    "knowBirthTimeDetail": "출생 시간을 알면 더 정확한 주기와 시점을 분석할 수 있습니다.",
    "searchCountries": "국가 검색",
    "greetingMorning": "좋은 아침입니다,",
    "greetingAfternoon": "좋은 오후입니다,",
    "greetingEvening": "편안한 저녁입니다,",
    "currentMoment": "지금 이 순간",
    "periodTimezoneUnknown": "시간대를 확인할 수 없습니다",
    "timezoneUnavailableNotice": "시간대 정보를 불러올 수 없습니다. 기본 설정을 사용합니다.",
    "yourDirection": "당신의 방향",
    "balancedResult": "균형을 이룸",
    "balancedHeading": "두 흐름이 대등합니다",
    "balancedExplanation": "어느 한쪽으로 기울지 않고 균형을 유지하고 있습니다. 내면의 소리에 조금 더 귀 기울여 보세요.",
    "insufficientHeading": "신호가 미약합니다",
    "insufficientBody": "명확한 흐름을 읽어내기에 정보가 부족합니다. 조금 뒤에 다시 시도해 보세요.",
    "percentageCaveat": "백분율은 상징적인 지표이며, 절대적인 확률이 아닙니다.",
    "resultBasis": "분석 기준",
    "everydayReflection": "일상의 성찰",
    "tryAnotherDirection": "다른 방향 탐색하기",
    "shareDisclaimer": "AstraCue 상징적 나침반 결과",
    "shareTooltip": "결과 공유",
    "shareUnavailable": "공유 기능을 사용할 수 없습니다",
    "saveAction": "저장",
    "saveFailedRetry": "저장에 실패했습니다. 다시 시도해 주세요.",
    "savingToHistory": "기록에 저장하는 중...",
    "historyToday": "오늘",
    "historySnapshot": "점술 기록 스냅샷",
    "historyPeriodPassed": "이 시간대는 이미 지났습니다",
    "historyCouldNotOpen": "기록을 열 수 없습니다",
    "historyNotEnoughData": "데이터가 부족하여 열 수 없습니다",
    "noReadings": "저장된 점술 기록이 없습니다.",
    "yourReadings": "나의 점술 기록",
    "backToHistory": "기록 목록으로 돌아가기",
    "viewHistory": "기록 보기",
    "openProfile": "프로필 열기",
    "profileTitle": "프로필",
    "profileConfirmTitle": "프로필 변경 확인",
    "profileNotSaved": "프로필이 저장되지 않았습니다",
    "changeLanguage": "언어 변경",
    "chooseLanguage": "언어 선택",
    "languageSetting": "언어 설정",
    "languageNotSaved": "언어 설정을 저장하지 못했습니다",
    "safetyHeading": "안전한 이용 수칙",
    "safetyIntro": "AstraCue를 건강하고 지혜롭게 활용하는 방법입니다.",
    "safetyTitle": "안전 수칙",
    "safetyScrollToContinue": "계속하려면 아래로 스크롤하세요",
    "acknowledge": "확인했습니다",
    "acknowledgementOnce": "최초 1회만 확인하시면 됩니다.",
    "ritualSafety": "마음 챙김 이용 안내",
    "prohibitedUses": "금지된 이용 행위",
    "medicalTitle": "의료 및 건강 관련 안내",
    "medicalDetail": "AstraCue는 의학적 진단, 치료, 처방을 대신하지 않습니다. 신체적·정신적 건강 문제는 반드시 전문 의료진과 상담하세요.",
    "financeTitle": "재정 및 투자 관련 안내",
    "financeDetail": "AstraCue는 투자, 대출, 자산 거래 등 재정적 결정을 지시하지 않습니다. 금융 관련 결정은 공인 금융 전문가와 상의하세요.",
    "legalTitle": "법률 관련 안내",
    "legalDetail": "AstraCue는 법률적 자문이나 소송 관련 지침을 제공하지 않습니다. 법적 분쟁은 공인 법률 전문가와 상의하세요.",
    "politicsTitle": "선거 및 정치 관련 안내",
    "politicsDetail": "본 서비스는 정치적 견해나 선거 결과에 관여하지 않으며 관련 예측을 제공하지 않습니다.",
    "harmTitle": "위해 및 위험 방지",
    "harmDetail": "자해, 타해, 범죄 행위 등 위험한 행동을 유도하거나 조장하는 용도로 본 서비스를 이용해서는 안 됩니다.",
    "navigationTitle": "항해 및 이동 안전",
    "navigationDetail": "차량 운전, 선박 항해, 항공기 조종 등 실제 이동 안전에 나침반 결과를 의존해서는 안 됩니다.",
    "importantLimitsHeading": "중요한 한계점",
    "importantLimitsBody": "상징적 패턴은 직관적 영감을 주는 도구일 뿐, 미래의 확실한 사실을 보장하지 않습니다.",
    "crisisSupport": "위기 상담 지원",
    "responsibleUseLink": "안전한 이용 안내 자세히 보기",
    "loadingBaZi": "사주 에너지 조율 중...",
    "loadingZiWei": "자미두수 명반 배치 중...",
    "loadingVedic": "베다 점성술 패턴 대조 중...",
    "loadingNumerology": "수비학적 파동 계산 중...",
    "loadingYinYang": "음양오행 균형 확인 중...",
    "loadingLocalTime": "지역 시각 및 천체 좌표 동기화 중...",
    "loadingLocalMoment": "현재 시간대의 기운을 읽는 중...",
    "loadingReassurance": "정확한 상징 매칭을 위해 잠시 호흡을 가다듬으세요...",
    "loadingModeYesNo": "선택의 양면성을 가만히 헤아려 보세요.",
    "loadingModeActWait": "때를 기다림과 나아감의 리듬을 느껴보세요.",
    "loadingModeAdvanceRetreat": "발걸음의 무게를 차분히 가늠해 보세요.",
    "loadingModeStayGo": "머묾과 떠남 사이의 고요를 바라보세요.",
    "loadingModeKeepLetGo": "마음속에 품을 것과 비울 것을 떠올려 보세요.",
    "loadingModeCommitWithdraw": "몰입과 한 걸음 물러섬의 경계를 짚어보세요.",
    "loadingModeForwardBackward": "시선의 방향을 조용히 바로잡아 보세요.",
    "loadingModeLeftRight": "좌우의 갈림길을 편견 없이 바라보세요.",
    "quotaExhaustedNotice": "오늘의 무료 점술 횟수를 모두 소진했습니다",
    "consentTitle": "동의, 미성년자 및 관계에 관한 원칙",
    "consentDetail": "타인의 동의나 자율성을 침해하거나, 양육권 및 후견인 관련 중대한 결정에 본 서비스를 이용해서는 안 됩니다.",
    "energyAccumulating": "우주의 에너지가 채워지고 있습니다",
    "watchAdPrompt": "동영상 광고를 시청하여 계속 진행할 수 있습니다",
    "watchAdButton": "광고 시청",
    "adUnlockedReward": "광고 시청 완료! 즉시 점술 1회 이용이 잠금 해제되었습니다",
    "periodElapsedHeading": "시간대가 지났습니다",
    "periodElapsedBody": "선택하신 시간대의 기운이 이미 흘러갔습니다. 현재 혹은 다가오는 시간대를 선택해 주세요.",
    "errorNothingRecorded": "기록된 점술이 없습니다."
}

ko.update(direct)

# Home Descriptions 00 to 29
home_descriptions_ko = [
    "오늘 우주는 당신에게 어떤 신호를 건네고 있을까요? 마음속 고민을 가만히 떠올리며 이 순간의 기운을 느껴보세요.",
    "두 갈래 길 앞에서 망설이고 계신가요? 오늘의 우주적 신호가 선택을 바라보는 새로운 시각을 열어줄 수 있습니다.",
    "별들이 당신 대신 결정을 내려주지는 않지만, 다음 발걸음을 비추는 뜻밖의 각도를 보여줄 수는 있습니다.",
    "앞으로 나아갈 길이 흐릿할 때는 잠시 멈추어 서 보세요. 오늘의 신호는 무엇을 비추고 있나요?",
    "모든 순간에는 그만의 고유한 에너지가 깃들어 있습니다. 고민을 떠올리며 이 순간이 이끄는 방향을 가만히 살펴보세요.",
    "어쩌면 우주는 속도를 조금 늦추라고 속삭이는지도 모릅니다. 결정을 내리기 전, 오늘 건네는 신호에 귀 기울여 보세요.",
    "갈림길에 서 계신가요? 오늘 하늘의 흐름이 당신의 마음에 어떤 울림을 주는지 살펴보세요.",
    "이 순간의 리듬에 가만히 귀 기울여 보세요. 오늘의 상징이 깊이 생각해 볼 만한 방향을 조용히 일러줄 수 있습니다.",
    "이 순간이 어떤 깨달음을 가져다줄까요? 신호를 살펴본 뒤, 당신의 내면을 믿고 담담히 나아가세요.",
    "우주가 건네는 작은 통찰이 생각을 정돈하는 데 도움을 줄 수 있습니다. 오늘 중요한 선택을 떠올리며 신호의 방향을 살펴보세요.",
    "같은 선택을 두고 오랫동안 고심하고 계신가요? 오늘의 우주 에너지가 어떤 본질을 조명하는지 살펴보세요.",
    "생각은 한쪽으로, 직관은 다른 쪽으로 향할 때. 오늘 당신을 둘러싼 상징적 패턴들을 가만히 짚어보세요.",
    "나아갈지, 기다릴지 망설여지시나요? 오늘의 흐름을 차분한 마음을 되찾기 위한 출발점으로 삼아보세요.",
    "바라보는 각도를 바꾸는 것만으로도 명확함이 찾아올 수 있습니다. 오늘 하늘의 고요한 움직임에 시선을 두어 보세요.",
    "자꾸만 마음에 맴도는 질문이 있나요? 오늘의 상징이 당신에게 무엇을 일깨워주는지 살펴보세요.",
    "같은 선택이라도 때에 따라 무게가 다르게 느껴집니다. 결정을 굳히기 전, 이 순간의 에너지를 담담히 바라보세요.",
    "지금은 길이 선명하게 보이지 않을 수 있습니다. 망설임 너머로 별들이 비추고 있는 것은 무엇일까요?",
    "충동적으로 움직이기 전에 잠시 숨을 고르세요. 오늘의 우주 신호가 무엇을 가리키는지 차분히 살펴보세요.",
    "모든 갈림길에서 서둘러 답을 내릴 필요는 없습니다. 오늘의 점술을 생각을 정리하는 여백으로 삼으세요.",
    "지금이 적절한 때인지 고민되시나요? 오늘의 흐름을 짚어보며 한층 안정된 시선을 찾아보세요.",
    "무엇이든 할 수 있을 것 같지만 확신이 서지 않을 때, 하늘의 배치가 새로운 시야를 열어줄 수 있습니다.",
    "선택은 오직 당신의 몫입니다. 오늘의 신호는 정말 중요한 것이 무엇인지 깨닫도록 돕는 길잡이입니다.",
    "망설임 탓에 다음 발걸음이 망설여질 때, 당신의 별자리와 오늘의 에너지가 무엇을 비추는지 살펴보세요.",
    "더 강한 확답보다는, 오늘의 상징과 고요히 마주하는 작은 여유가 필요한 순간일 수 있습니다.",
    "직관은 행동을 재촉하나요, 아니면 기다림을 권하나요? 오늘 우주의 리듬을 가만히 따라가 보세요.",
    "바람과 두려움 사이에는 잠시 숨을 돌릴 여백이 있습니다. 오늘의 신호를 길잡이 삼아 마음을 다시 들여다보세요.",
    "질문은 이미 당신 안에 있습니다. 이제 이 순간에 집중해 보세요. 오늘 천체의 신호는 무엇을 말하고 있나요?",
    "결정이 복잡하게 느껴질 때, 오래된 상징과 오늘이라는 시간이 뜻밖의 명료함을 건넬 수 있습니다.",
    "지금은 한 걸음 다가설 때일까요, 아니면 한 발 물러설 때일까요? 선택을 둘러싼 에너지의 결을 살펴보세요.",
    "여기서 완벽한 확신을 얻지 않아도 괜찮습니다. 마음을 가라앉히고, 우주의 힌트와 함께 생각을 가다듬으세요."
]
for i, desc in enumerate(home_descriptions_ko):
    ko[f"homeDescription{i:02d}"] = desc

# Energy insights pools
energy_pools = {
    "Radiant": [
        "오늘의 상징적 에너지는 생동감 있게 빛나며, 자신감과 맑은 시야를 밝혀줍니다.",
        "기운이 한껏 고조되는 날입니다. 내면의 맑은 빛에 집중하며 주위를 둘러보세요.",
        "생명력이 넘쳐흐릅니다. 마음속 품어둔 뜻을 조심스레 펼쳐보기에 좋은 날입니다.",
        "오늘의 하늘은 환한 명료함을 비춥니다. 의구심이 옅어지고 결의가 돋보입니다.",
        "찬란한 흐름 속에서 당신의 긍정적인 파동이 주변과 조화롭게 공명합니다.",
        "빛이 가장 밝을 때입니다. 명확한 시야를 바탕으로 다음 계획을 세워보세요.",
        "마음속 열정이 따뜻하게 타오릅니다. 당신이 가진 긍정의 힘을 믿으세요.",
        "환한 에너지 속에서 자연스러운 통찰이 피어납니다. 영감을 놓치지 마세요."
    ],
    "Steady": [
        "오늘의 기운은 단단하고 안정적이어서, 차분한 판단과 묵직한 발걸음을 지탱해 줍니다.",
        "흔들리지 않는 대지처럼 마음이 평온합니다. 서두르지 않고 기본을 다지기에 적합합니다.",
        "주변의 소음 속에서도 중심을 지키기 수월한 날입니다. 차분히 순서를 정해보세요.",
        "안정된 흐름이 당신의 생각을 가지런히 정돈해 줍니다. 현실적인 시각을 유지하세요.",
        "지속 가능한 힘이 내면에 머물고 있습니다. 긴 호흡으로 멀리 바라보세요.",
        "뿌리가 깊은 나무처럼 안정감이 있습니다. 조급해하지 않아도 충분합니다.",
        "평온함 속에서 일상의 리듬이 지켜집니다. 꾸준함이 가장 큰 힘입니다.",
        "마음의 균형이 단단히 잡혀 있습니다. 계획한 바를 차분히 이어가세요."
    ],
    "Restless": [
        "에너지가 잔잔히 일렁이며, 내면의 호기심과 성급함을 동시에 자극할 수 있습니다.",
        "마음이 바쁘게 움직이는 날입니다. 성급히 결론을 내리기보다는 생각을 관찰하세요.",
        "변화의 바람이 불고 있습니다. 충동에 휩쓸리지 않도록 잠시 호흡을 가다듬으세요.",
        "다양한 생각이 교차할 수 있습니다. 한 번에 하나씩 차근차근 매듭을 지어보세요.",
        "움직이고 싶은 욕구가 커질 수 있습니다. 흩어진 에너지를 한곳으로 모아보세요."
    ],
    "Fading": [
        "에너지가 서서히 잦아들며, 다음 주기를 맞이하기 위한 쉼과 마무리를 권합니다.",
        "달이 차오르다 기우는 것처럼, 지금은 힘을 아끼고 에너지를 비축할 때입니다.",
        "무리하게 밀어붙이기보다는 미뤄둔 정리를 하며 마음을 비워내기에 적합합니다.",
        "서서히 가라앉는 기운을 자연스레 받아들이세요. 휴식 또한 전진의 일부입니다.",
        "활동성을 잠시 내려놓고, 그동안 지나온 과정들을 고요히 매듭지어 보세요."
    ],
    "Turbulent": [
        "기운이 거세게 요동치고 있어, 감정의 파도에 휩쓸리지 않도록 닻을 내려야 합니다.",
        "예상치 못한 감정이 불쑥 솟아오를 수 있습니다. 즉각적인 반응을 멈추고 거리를 두세요.",
        "바람이 세차게 부는 날입니다. 중요한 결정은 바람이 잦아든 뒤로 미루는 편이 지혜롭습니다.",
        "상충하는 생각들이 부딪힐 수 있습니다. 감정이 가라앉을 때까지 판단을 보류하세요.",
        "혼란스러울수록 내면의 침묵에 머무르세요. 격렬한 파도 뒤에는 잔잔함이 찾아옵니다."
    ],
    "Still": [
        "깊은 호수처럼 고요한 에너지입니다. 내면의 목소리를 듣기에 더없이 좋은 시간입니다.",
        "외부의 자극이 잦아들고 침묵이 깃듭니다. 당신의 가장 깊은 본심을 들여다보세요.",
        "움직임이 멈춘 듯한 고요 속에서, 비로소 보이지 않던 중요한 진실이 드러납니다.",
        "말을 아끼고 귀를 기울이기에 알맞은 날입니다. 마음의 평화를 소중히 지키세요.",
        "고요함은 멈춤이 아닌 깊은 채움입니다. 잔잔한 수면에 마음을 비추어 보세요."
    ],
    "Quiet": [
        "오늘의 상징적 에너지는 내면으로 향하며, 조용히 돌아볼 여백을 만듭니다.",
        "오늘의 우주 리듬은 안으로 흐릅니다. 고요함 속에서 소음에 가려졌던 진심을 발견할 수 있습니다.",
        "하늘에 정적의 기운이 머뭅니다. 생각이 자연스레 가라앉을 시간을 가져보세요.",
        "은은한 평온이 흐르는 날입니다. 서두르기보다 주변의 기운을 차분히 관찰해 보세요.",
        "오늘의 신호는 회고를 권합니다. 잠시 멈추어 서는 것도 나아가는 과정의 일부입니다.",
        "마음이 차분해질수록, 당신 안의 나침반이 내는 소리가 더 또렷하게 들려옵니다.",
        "오늘의 에너지는 성급히 답을 내리기 전에 귀를 기울일 넉넉한 틈을 선사합니다.",
        "신호가 늘 큰 소리로 다가오는 것은 아닙니다. 오늘은 천천히 걸을 때 더 잘 보입니다."
    ],
    "Soft": [
        "오늘의 상징적 에너지는 부드럽게 흐르며, 다정한 시선과 조심스러운 첫걸음을 품어줍니다.",
        "마음의 긴장을 풀고 쉬어가기 좋은 날입니다. 작은 친절이 큰 힘이 되어줍니다.",
        "유연한 흐름이 마음을 감쌉니다. 고집을 내려놓고 순리에 맡겨보세요.",
        "따스한 햇살 같은 기운이 깃들어 있습니다. 스스로를 너그럽게 대하세요.",
        "서두르지 않아도 모든 것은 제자리를 찾아갑니다. 마음의 여유를 지키세요.",
        "부드러운 대화 속에서 오해가 풀릴 수 있습니다. 온화한 태도를 유지하세요.",
        "감정의 날을 세우지 않고 둥글게 보듬기에 적합한 평화로운 날입니다.",
        "조용한 위로가 마음에 머뭅니다. 작은 일상 속 따뜻함을 음미해 보세요."
    ],
    "Flowing": [
        "에너지가 막힘없이 유려하게 흐르며, 유연한 적응과 자연스러운 전환을 돕습니다.",
        "강물이 바다로 흐르듯 자연스러운 전개가 이어집니다. 흐름에 몸을 맡기세요.",
        "변화에 저항하기보다 유연하게 맞춰갈 때 가장 좋은 길이 열립니다.",
        "막혔던 생각의 물꼬가 트이는 날입니다. 자유롭게 생각을 확장해 보세요.",
        "순조로운 리듬이 유지됩니다. 억지로 힘을 주지 않아도 일이 자연스레 풀려갑니다.",
        "유연한 태도가 뜻밖의 해결책을 가져다줍니다. 열린 마음을 가져보세요.",
        "경직된 틀을 벗어나 가볍게 흘러가 보세요. 새로움이 당신을 반깁니다.",
        "흐름을 타는 지혜가 빛을 발합니다. 순리를 믿고 유연하게 움직이세요."
    ],
    "Focused": [
        "에너지가 한 점으로 뚜렷이 모이며, 깊은 몰입과 명료한 주의 집중을 이끕니다.",
        "불필요한 잔가지가 쳐지고 본질이 선명해지는 날입니다. 핵심에 집중하세요.",
        "산만함이 줄어들고 마음의 과녁이 뚜렷해집니다. 우선순위를 먼저 매듭지으세요.",
        "깊이 파고들기에 최적의 기운입니다. 차분히 한 가지 일에 마음을 쏟아보세요.",
        "명확한 통찰이 찾아옵니다. 흐릿했던 문제의 본질을 꿰뚫어 볼 수 있습니다.",
        "집중력이 돋보이는 시간입니다. 중요한 과제를 해결하기에 좋은 흐름입니다.",
        "주의가 흩어지지 않도록 환경을 정돈하세요. 몰입의 결실이 큽니다.",
        "군더더기를 덜어내고 정말 중요한 목표 하나를 향해 나아가세요."
    ],
    "Lively": [
        "활기찬 에너지가 가득 차올라, 생동감 넘치는 교류와 경쾌한 발걸음을 재촉합니다.",
        "생동하는 기운이 마음에 활력을 불어넣습니다. 가벼운 마음으로 시작해 보세요.",
        "새로운 아이디어가 샘솟는 날입니다. 주변과 긍정적인 자극을 주고받으세요.",
        "발걸음이 한결 가볍습니다. 망설이던 일에 활기찬 활력을 불어넣어 보세요.",
        "주변 사람들과의 소통 속에서 기분 좋은 활력이 피어납니다.",
        "기분 좋은 호기심이 일어납니다. 새로운 시도를 두려워하지 마세요.",
        "밝은 파동이 주변을 환하게 밝힙니다. 당신의 활기를 나누어 보세요.",
        "활력이 넘치되 들뜨지 않도록 조절하세요. 즐거운 리듬을 만끽하세요."
    ],
    "Bright": [
        "하늘이 맑고 환한 빛으로 가득하여, 긍정적인 전망과 따뜻한 희망을 비춥니다.",
        "구름이 걷히고 햇살이 비추듯 마음에 명료함이 깃듭니다.",
        "낙관적인 시각이 힘을 발휘하는 날입니다. 긍정의 가능성을 열어두세요.",
        "환한 빛 아래에서 의구심이 눈 녹듯 사라집니다. 자신감을 가지세요.",
        "따뜻한 온기가 마음을 채웁니다. 감사한 마음으로 하루를 대하세요.",
        "밝은 시야 속에서 새로운 기회가 눈에 띕니다. 시선을 넓게 두세요.",
        "주변의 어둠을 밝히는 온화한 빛이 당신과 함께합니다.",
        "희망적인 직관이 반짝입니다. 맑은 마음으로 결정을 마주하세요."
    ]
}

for prefix, list_of_text in energy_pools.items():
    for i, t in enumerate(list_of_text):
        ko[f"energy{prefix}{i:02d}"] = t

# Sanity check: every single key in ref must be in ko
missing_keys = set(ref.keys()) - set(ko.keys())
if missing_keys:
    print(f"STILL MISSING: {len(missing_keys)} keys -> {missing_keys}")
else:
    print("PERFECT MATCH! All 364 keys present in ko!")

# Verify placeholders match
braces = r'\{(\w+)\}'
import re
for k, v in ref.items():
    en_val = v['en']
    ko_val = ko.get(k, '')
    en_p = set(re.findall(braces, en_val))
    ko_p = set(re.findall(braces, ko_val))
    if en_p != ko_p:
        print(f"PLACEHOLDER MISMATCH in {k}: en={en_p}, ko={ko_p}")

final_ko = {"@@locale": "ko"}
for k in ref.keys():
    final_ko[k] = ko[k]

with open('mobile_app/lib/l10n/app_ko.arb', 'w', encoding='utf-8') as f:
    json.dump(final_ko, f, ensure_ascii=False, indent=2)

print(f"Saved app_ko.arb with {len(final_ko)} keys successfully.")

