# Static launch artwork for iOS and Android 11 or earlier. Android 12+ uses
# the matching animated vector generated by generate_animated_launch_vector.ps1.
$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Drawing

$appRoot = Split-Path -Parent $PSScriptRoot
$androidLaunch = Join-Path $appRoot 'android/app/src/main/res/drawable-nodpi'
$iosLaunch = Join-Path $appRoot 'ios/Runner/Assets.xcassets/LaunchImage.imageset'
$fontPath = Join-Path $appRoot 'assets/fonts/NotoSans-Regular.ttf'
New-Item -ItemType Directory -Path $androidLaunch -Force | Out-Null

$privateFonts = [System.Drawing.Text.PrivateFontCollection]::new()
$privateFonts.AddFontFile($fontPath)
$base = [System.Drawing.Bitmap]::new(600, 300, [System.Drawing.Imaging.PixelFormat]::Format32bppArgb)
try {
    $graphics = [System.Drawing.Graphics]::FromImage($base)
    try {
        $graphics.Clear([System.Drawing.Color]::Transparent)
        $graphics.SmoothingMode = [System.Drawing.Drawing2D.SmoothingMode]::AntiAlias
        $graphics.PixelOffsetMode = [System.Drawing.Drawing2D.PixelOffsetMode]::HighQuality

        $star = [System.Drawing.Drawing2D.GraphicsPath]::new()
        $star.StartFigure()
        $star.AddBezier([System.Drawing.PointF]::new(300, 18), [System.Drawing.PointF]::new(304, 33),
            [System.Drawing.PointF]::new(309, 38), [System.Drawing.PointF]::new(324, 43))
        $star.AddBezier([System.Drawing.PointF]::new(324, 43), [System.Drawing.PointF]::new(309, 48),
            [System.Drawing.PointF]::new(304, 53), [System.Drawing.PointF]::new(300, 68))
        $star.AddBezier([System.Drawing.PointF]::new(300, 68), [System.Drawing.PointF]::new(296, 53),
            [System.Drawing.PointF]::new(291, 48), [System.Drawing.PointF]::new(276, 43))
        $star.AddBezier([System.Drawing.PointF]::new(276, 43), [System.Drawing.PointF]::new(291, 38),
            [System.Drawing.PointF]::new(296, 33), [System.Drawing.PointF]::new(300, 18))
        $star.CloseFigure()
        $starGlow = [System.Drawing.Pen]::new([System.Drawing.Color]::FromArgb(30, 216, 182, 106), 4)
        $starFill = [System.Drawing.Drawing2D.LinearGradientBrush]::new(
            [System.Drawing.RectangleF]::new(276, 18, 48, 50),
            [System.Drawing.Color]::FromArgb(241, 212, 134),
            [System.Drawing.Color]::FromArgb(196, 155, 84), 90
        )
        $path = [System.Drawing.Drawing2D.GraphicsPath]::new()
        $format = [System.Drawing.StringFormat]::GenericDefault.Clone()
        try {
            $graphics.DrawPath($starGlow, $star)
            $graphics.FillPath($starFill, $star)

            $format.FormatFlags = $format.FormatFlags -bor [System.Drawing.StringFormatFlags]::NoWrap
            $path.AddString('AstraCue', $privateFonts.Families[0],
                [int][System.Drawing.FontStyle]::Regular, 96,
                [System.Drawing.PointF]::new(0, 0), $format)
            $bounds = $path.GetBounds()
            $translation = [System.Drawing.Drawing2D.Matrix]::new()
            try {
                $translation.Translate((600 - $bounds.Width) / 2 - $bounds.X, 93 - $bounds.Y)
                $path.Transform($translation)
            } finally {
                $translation.Dispose()
            }

            $blueGlow = [System.Drawing.Pen]::new([System.Drawing.Color]::FromArgb(18, 78, 179, 232), 16)
            $goldGlow = [System.Drawing.Pen]::new([System.Drawing.Color]::FromArgb(16, 216, 182, 106), 9)
            $gradient = [System.Drawing.Drawing2D.LinearGradientBrush]::new(
                [System.Drawing.RectangleF]::new(70, 85, 460, 110),
                [System.Drawing.Color]::FromArgb(191, 221, 241),
                [System.Drawing.Color]::FromArgb(231, 203, 141), 0
            )
            $blend = [System.Drawing.Drawing2D.ColorBlend]::new(3)
            $blend.Colors = [System.Drawing.Color[]]@(
                [System.Drawing.Color]::FromArgb(191, 221, 241),
                [System.Drawing.Color]::FromArgb(244, 247, 252),
                [System.Drawing.Color]::FromArgb(231, 203, 141)
            )
            $blend.Positions = [single[]]@(0, 0.48, 1)
            $gradient.InterpolationColors = $blend
            try {
                $graphics.DrawPath($blueGlow, $path)
                $graphics.DrawPath($goldGlow, $path)
                $graphics.FillPath($gradient, $path)
            } finally {
                $gradient.Dispose()
                $goldGlow.Dispose()
                $blueGlow.Dispose()
            }

        } finally {
            $format.Dispose()
            $path.Dispose()
            $starFill.Dispose()
            $starGlow.Dispose()
            $star.Dispose()
        }
    } finally {
        $graphics.Dispose()
    }

    function Export-LaunchImage(
        [string]$path, [int]$width, [int]$height,
        [System.Drawing.Rectangle]$destination
    ) {
        $bitmap = [System.Drawing.Bitmap]::new($width, $height, [System.Drawing.Imaging.PixelFormat]::Format32bppArgb)
        try {
            $drawing = [System.Drawing.Graphics]::FromImage($bitmap)
            try {
                $drawing.Clear([System.Drawing.Color]::Transparent)
                $drawing.InterpolationMode = [System.Drawing.Drawing2D.InterpolationMode]::HighQualityBicubic
                $drawing.PixelOffsetMode = [System.Drawing.Drawing2D.PixelOffsetMode]::HighQuality
                $drawing.DrawImage($base, $destination)
            } finally {
                $drawing.Dispose()
            }
            $bitmap.Save($path, [System.Drawing.Imaging.ImageFormat]::Png)
        } finally {
            $bitmap.Dispose()
        }
    }

    Export-LaunchImage (Join-Path $androidLaunch 'launch_wordmark.png') `
        600 300 ([System.Drawing.Rectangle]::new(0, 0, 600, 300))
    # Android 12 masks the outer portion of the square splash icon.
    Export-LaunchImage (Join-Path $androidLaunch 'launch_wordmark_system.png') `
        600 600 ([System.Drawing.Rectangle]::new(60, 180, 480, 240))

    foreach ($scale in 1..3) {
        $suffix = if ($scale -eq 1) { '' } else { "@$($scale)x" }
        $width = 200 * $scale
        $height = 100 * $scale
        Export-LaunchImage (Join-Path $iosLaunch "LaunchImage$suffix.png") `
            $width $height ([System.Drawing.Rectangle]::new(0, 0, $width, $height))
    }
    Write-Output 'Generated native launch wordmarks for Android and iOS.'
} finally {
    $base.Dispose()
    $privateFonts.Dispose()
}
