# Static launch artwork for iOS and Android 11 or earlier. Android 12+ uses
# the matching animated vector generated by generate_animated_launch_vector.ps1.
$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Drawing

$appRoot = Split-Path -Parent $PSScriptRoot
$androidLaunch = Join-Path $appRoot 'android/app/src/main/res/drawable-nodpi'
$iosLaunch = Join-Path $appRoot 'ios/Runner/Assets.xcassets/LaunchImage.imageset'
$fontPath = Join-Path $appRoot 'assets/fonts/NotoSans-Regular.ttf'
New-Item -ItemType Directory -Path $androidLaunch -Force | Out-Null

$privateFonts = [System.Drawing.Text.PrivateFontCollection]::new()
$privateFonts.AddFontFile($fontPath)
$base = [System.Drawing.Bitmap]::new(600, 300, [System.Drawing.Imaging.PixelFormat]::Format32bppArgb)
try {
    $graphics = [System.Drawing.Graphics]::FromImage($base)
    try {
        $graphics.Clear([System.Drawing.Color]::Transparent)
        $graphics.SmoothingMode = [System.Drawing.Drawing2D.SmoothingMode]::AntiAlias
        $graphics.PixelOffsetMode = [System.Drawing.Drawing2D.PixelOffsetMode]::HighQuality

        $star = [System.Drawing.Drawing2D.GraphicsPath]::new()
        $star.AddPolygon([System.Drawing.PointF[]]@(
            [System.Drawing.PointF]::new(300, 23),
            [System.Drawing.PointF]::new(304, 39),
            [System.Drawing.PointF]::new(319, 43),
            [System.Drawing.PointF]::new(304, 47),
            [System.Drawing.PointF]::new(300, 63),
            [System.Drawing.PointF]::new(296, 47),
            [System.Drawing.PointF]::new(281, 43),
            [System.Drawing.PointF]::new(296, 39)
        ))
        $starGlow = [System.Drawing.Pen]::new([System.Drawing.Color]::FromArgb(35, 216, 182, 106), 10)
        $starFill = [System.Drawing.SolidBrush]::new([System.Drawing.Color]::FromArgb(216, 182, 106))
        $path = [System.Drawing.Drawing2D.GraphicsPath]::new()
        $format = [System.Drawing.StringFormat]::GenericDefault.Clone()
        try {
            $graphics.DrawPath($starGlow, $star)
            $graphics.FillPath($starFill, $star)

            $format.FormatFlags = $format.FormatFlags -bor [System.Drawing.StringFormatFlags]::NoWrap
            $path.AddString('AstraCue', $privateFonts.Families[0],
                [int][System.Drawing.FontStyle]::Regular, 96,
                [System.Drawing.PointF]::new(0, 0), $format)
            $bounds = $path.GetBounds()
            $translation = [System.Drawing.Drawing2D.Matrix]::new()
            try {
                $translation.Translate((600 - $bounds.Width) / 2 - $bounds.X, 93 - $bounds.Y)
                $path.Transform($translation)
            } finally {
                $translation.Dispose()
            }

            $blueGlow = [System.Drawing.Pen]::new([System.Drawing.Color]::FromArgb(18, 78, 179, 232), 16)
            $goldGlow = [System.Drawing.Pen]::new([System.Drawing.Color]::FromArgb(16, 216, 182, 106), 9)
            $gradient = [System.Drawing.Drawing2D.LinearGradientBrush]::new(
                [System.Drawing.RectangleF]::new(70, 85, 460, 110),
                [System.Drawing.Color]::FromArgb(191, 221, 241),
                [System.Drawing.Color]::FromArgb(231, 203, 141), 0
            )
            $blend = [System.Drawing.Drawing2D.ColorBlend]::new(3)
            $blend.Colors = [System.Drawing.Color[]]@(
                [System.Drawing.Color]::FromArgb(191, 221, 241),
                [System.Drawing.Color]::FromArgb(244, 247, 252),
                [System.Drawing.Color]::FromArgb(231, 203, 141)
            )
            $blend.Positions = [single[]]@(0, 0.48, 1)
            $gradient.InterpolationColors = $blend
            try {
                $graphics.DrawPath($blueGlow, $path)
                $graphics.DrawPath($goldGlow, $path)
                $graphics.FillPath($gradient, $path)
            } finally {
                $gradient.Dispose()
                $goldGlow.Dispose()
                $blueGlow.Dispose()
            }

            $ringPen = [System.Drawing.Pen]::new([System.Drawing.Color]::FromArgb(72, 98, 183, 232), 2)
            $goldDot = [System.Drawing.SolidBrush]::new([System.Drawing.Color]::FromArgb(216, 182, 106))
            $blueDot = [System.Drawing.SolidBrush]::new([System.Drawing.Color]::FromArgb(98, 183, 232))
            try {
                $graphics.DrawEllipse($ringPen, 267, 222, 66, 66)
                foreach ($index in 0..2) {
                    $angle = $index * [math]::PI * 2 / 3
                    $x = 300 + [math]::Cos($angle) * 33
                    $y = 255 + [math]::Sin($angle) * 33
                    $radius = if ($index -eq 0) { 7 } else { 6 }
                    $brush = if ($index -eq 0) { $goldDot } else { $blueDot }
                    $graphics.FillEllipse($brush, $x - $radius, $y - $radius, 2 * $radius, 2 * $radius)
                }
            } finally {
                $blueDot.Dispose()
                $goldDot.Dispose()
                $ringPen.Dispose()
            }
        } finally {
            $format.Dispose()
            $path.Dispose()
            $starFill.Dispose()
            $starGlow.Dispose()
            $star.Dispose()
        }
    } finally {
        $graphics.Dispose()
    }

    function Export-LaunchImage(
        [string]$path, [int]$width, [int]$height,
        [System.Drawing.Rectangle]$destination
    ) {
        $bitmap = [System.Drawing.Bitmap]::new($width, $height, [System.Drawing.Imaging.PixelFormat]::Format32bppArgb)
        try {
            $drawing = [System.Drawing.Graphics]::FromImage($bitmap)
            try {
                $drawing.Clear([System.Drawing.Color]::Transparent)
                $drawing.InterpolationMode = [System.Drawing.Drawing2D.InterpolationMode]::HighQualityBicubic
                $drawing.PixelOffsetMode = [System.Drawing.Drawing2D.PixelOffsetMode]::HighQuality
                $drawing.DrawImage($base, $destination)
            } finally {
                $drawing.Dispose()
            }
            $bitmap.Save($path, [System.Drawing.Imaging.ImageFormat]::Png)
        } finally {
            $bitmap.Dispose()
        }
    }

    Export-LaunchImage (Join-Path $androidLaunch 'launch_wordmark.png') `
        600 300 ([System.Drawing.Rectangle]::new(0, 0, 600, 300))
    # Android 12 masks the outer portion of the square splash icon.
    Export-LaunchImage (Join-Path $androidLaunch 'launch_wordmark_system.png') `
        600 600 ([System.Drawing.Rectangle]::new(60, 180, 480, 240))

    foreach ($scale in 1..3) {
        $suffix = if ($scale -eq 1) { '' } else { "@$($scale)x" }
        $width = 200 * $scale
        $height = 100 * $scale
        Export-LaunchImage (Join-Path $iosLaunch "LaunchImage$suffix.png") `
            $width $height ([System.Drawing.Rectangle]::new(0, 0, $width, $height))
    }
    Write-Output 'Generated native launch wordmarks for Android and iOS.'
} finally {
    $base.Dispose()
    $privateFonts.Dispose()
}
