import 'package:decision_compass/local_engine/astronomy/astronomy.dart';
import 'package:decision_compass/local_engine/time/local_time.dart';
import 'package:flutter_test/flutter_test.dart';

import 'corpus_loader.dart';

/// Differential tests for the offline astronomy module.
///
/// Expectations come from `astronomy_corpus.json`, generated by running the
/// Node engine's own `src/astronomy.js` over Astronomy Engine 2.1.19. The
/// tolerance is deliberately tiny: the VSOP and lunar series are ported term
/// for term in the same summation order, so anything beyond the last few bits
/// means the port drifted rather than the model being approximate.
void main() {
  final corpus = loadCorpus('astronomy_corpus.json');

  /// Longitudes are degrees in [0, 360); 1e-9° is under a microarcsecond.
  const double tolerance = 1e-9;

  BirthContext birthFrom(Map<String, dynamic> profile) => birthContext(
    birthDate: profile['birthDate'] as String,
    birthTime: profile['birthTime'] as String?,
    birthCountry: profile['birthCountry'] as String?,
    birthTimezone: profile['birthTimezone'] as String?,
  );

  test('geocentric ecliptic longitudes match for every body', () {
    for (final row in rows(corpus, 'longitudes')) {
      final ms = asDouble(row['ms']);
      final values = row['values'] as Map<String, dynamic>;
      for (final entry in values.entries) {
        expect(
          longitudeOf(entry.key, ms),
          closeTo(asDouble(entry.value), tolerance),
          reason: '${entry.key} @ ${row['iso']}',
        );
      }
    }
  });

  test('sky snapshot, Mercury speed and the cosmic module match', () {
    for (final row in rows(corpus, 'sky')) {
      final sky = skyAt(asDouble(row['ms']));
      final positions = row['positions'] as Map<String, dynamic>;
      for (final entry in positions.entries) {
        expect(
          sky.positions[entry.key],
          closeTo(asDouble(entry.value), tolerance),
          reason: '${entry.key} @ ${row['iso']}',
        );
      }
      expect(
        sky.mercurySpeed,
        closeTo(asDouble(row['mercurySpeed']), tolerance),
        reason: 'mercury speed @ ${row['iso']}',
      );
      expect(
        sky.evaluatedAtUtc,
        row['evaluatedAtUtc'],
        reason: 'iso @ ${row['iso']}',
      );

      final expected = row['cosmic'] as Map<String, dynamic>;
      final actual = cosmic(sky);
      expect(
        actual.status,
        expected['status'],
        reason: 'cosmic status @ ${row['iso']}',
      );
      expect(
        actual.evidence.a,
        closeTo(asDouble(expected['a']), tolerance),
        reason: 'cosmic a @ ${row['iso']}',
      );
      expect(
        actual.evidence.c,
        closeTo(asDouble(expected['c']), tolerance),
        reason: 'cosmic c @ ${row['iso']}',
      );
      expect(
        actual.evidence.coverage,
        closeTo(asDouble(expected['coverage']), tolerance),
        reason: 'cosmic coverage @ ${row['iso']}',
      );
    }
  });

  test('aspect geometry, orb strength and axis vectors match', () {
    for (final row in rows(corpus, 'aspects')) {
      final hit = aspect(
        asDouble(row['transit']),
        asDouble(row['natal']),
        row['body'] as String,
      );
      final label = '${row['body']} ${row['transit']}/${row['natal']}';
      expect(hit.angle, row['angle'], reason: '$label angle');
      expect(
        hit.strength,
        closeTo(asDouble(row['strength']), tolerance),
        reason: '$label strength',
      );
      expect(hit.a, closeTo(asDouble(row['a']), tolerance), reason: '$label a');
      expect(hit.c, closeTo(asDouble(row['c']), tolerance), reason: '$label c');
    }
  });

  test(
    'natal sky keeps only stable features when the birth hour is unknown',
    () {
      for (final row in rows(corpus, 'natal')) {
        final profile = row['profile'] as Map<String, dynamic>;
        final natal = natalSky(birthFrom(profile));
        final label = profile.toString();
        expect(natal.status, row['status'], reason: '$label status');
        expect(natal.method, row['method'], reason: '$label method');
        expect(
          natal.sampleCount,
          row['sampleCount'],
          reason: '$label sample count',
        );

        final expectedPositions = row['positions'] as Map<String, dynamic>;
        expect(
          natal.positions.keys.toSet(),
          expectedPositions.keys.toSet(),
          reason: '$label stable bodies',
        );
        for (final entry in expectedPositions.entries) {
          expect(
            natal.positions[entry.key],
            closeTo(asDouble(entry.value), tolerance),
            reason: '$label ${entry.key}',
          );
        }

        final expectedRanges = row['ranges'] as Map<String, dynamic>;
        for (final entry in expectedRanges.entries) {
          final want = entry.value as Map<String, dynamic>;
          final got = natal.ranges[entry.key]!;
          expect(
            got['stable'],
            want['stable'],
            reason: '$label ${entry.key} stable',
          );
          expect(
            got['spanDegrees'] as double,
            closeTo(asDouble(want['spanDegrees']), tolerance),
            reason: '$label ${entry.key} span',
          );
          expect(
            got['minLongitude'] as double,
            closeTo(asDouble(want['minLongitude']), tolerance),
            reason: '$label ${entry.key} min',
          );
          expect(
            got['maxLongitude'] as double,
            closeTo(asDouble(want['maxLongitude']), tolerance),
            reason: '$label ${entry.key} max',
          );
        }
      }
    },
  );

  test('western module matches for every category and birth profile', () {
    for (final row in rows(corpus, 'western')) {
      final profile = row['profile'] as Map<String, dynamic>;
      final natal = natalSky(birthFrom(profile));
      final sky = skyAt(parseInstant(row['iso']));
      final actual = western(sky, natal, row['category'] as String);
      final label =
          '${profile['birthDate']} ${row['category']} @ ${row['iso']}';
      expect(actual.status, row['status'], reason: '$label status');
      expect(
        actual.evidence.a,
        closeTo(asDouble(row['a']), tolerance),
        reason: '$label a',
      );
      expect(
        actual.evidence.c,
        closeTo(asDouble(row['c']), tolerance),
        reason: '$label c',
      );
      expect(
        actual.evidence.coverage,
        closeTo(asDouble(row['coverage']), tolerance),
        reason: '$label coverage',
      );
    }
  });

  test('category weight profiles are well formed', () {
    validateWesternProfiles();
  });
}
