import 'package:decision_compass/local_engine/time/local_time.dart';
import 'package:decision_compass/local_engine/time/tzdb.dart';
import 'package:flutter_test/flutter_test.dart';

import 'corpus_loader.dart';

/// Differential tests for the offline time layer.
///
/// Every expectation comes from `time_corpus.json`, which is generated by
/// running the real Node engine's own `src/time.js`. Nothing here is a
/// hand-written guess about what the answer should be.
void main() {
  final corpus = loadCorpus('time_corpus.json');

  test('bundled tzdb matches the version the Node engine reports', () {
    expect(tzdbVersion, corpus['tzdbVersion']);
  });

  test('country list and per-country zone candidates match', () {
    expect(tzdbCountries(), asStrings(corpus['countries']));
    final expected = corpus['zonesForCountry'] as Map<String, dynamic>;
    for (final entry in expected.entries) {
      expect(
        zonesForCountry(entry.key),
        asStrings(entry.value),
        reason: 'zones for ${entry.key}',
      );
    }
  });

  test('unpacked zone tables match moment-timezone', () {
    final tables = corpus['zoneTables'] as Map<String, dynamic>;
    for (final entry in tables.entries) {
      final zone = lookupZone(entry.key);
      expect(zone, isNotNull, reason: entry.key);
      final expected = entry.value as Map<String, dynamic>;
      expect(
        zone!.offsets,
        asDoubles(expected['offsets']),
        reason: '${entry.key} offsets',
      );
      expect(
        zone.untils.length,
        expected['untilCount'],
        reason: '${entry.key} until count',
      );
      // A null entry is the open-ended final until, which JSON cannot carry.
      final firstUntils = (expected['firstUntils'] as List<dynamic>);
      for (var i = 0; i < firstUntils.length; i++) {
        final want = firstUntils[i];
        expect(
          zone.untils[i],
          want == null ? double.infinity : asDouble(want),
          reason: '${entry.key} until $i',
        );
      }
      final lastFinite = expected['lastFiniteUntil'];
      if (lastFinite != null) {
        expect(
          zone.untils[zone.untils.length - 2],
          asDouble(lastFinite),
          reason: '${entry.key} last finite until',
        );
      }
      expect(
        zone.untils.last,
        double.infinity,
        reason: '${entry.key} open end',
      );
    }
  });

  test('localAt reproduces every field, offset and ISO rendering', () {
    for (final row in rows(corpus, 'localAt')) {
      final local = localAt(asDouble(row['ms']), row['zone'] as String);
      final label = '${row['zone']} @ ${row['iso']}';
      expect(local.year, row['year'], reason: '$label year');
      expect(local.month, row['month'], reason: '$label month');
      expect(local.day, row['day'], reason: '$label day');
      expect(local.hour, row['hour'], reason: '$label hour');
      expect(local.minute, row['minute'], reason: '$label minute');
      expect(local.second, row['second'], reason: '$label second');
      expect(local.date, row['date'], reason: '$label date');
      expect(local.clock, row['clock'], reason: '$label clock');
      expect(
        local.offsetSeconds,
        asDouble(row['offsetSeconds']),
        reason: '$label offset',
      );
      expect(local.iso, row['isoLocal'], reason: '$label iso');
    }
  });

  test('DST gaps yield no instant and folds yield two', () {
    for (final row in rows(corpus, 'localCandidates')) {
      final actual = localCandidates(
        row['date'] as String,
        row['clock'] as String,
        row['zone'] as String,
      );
      expect(
        actual,
        asDoubles(row['instants']),
        reason: '${row['zone']} ${row['date']} ${row['clock']}',
      );
    }
  });

  test('hour branch mapping and period bounds match', () {
    final expected = (corpus['hourBranch'] as List<dynamic>).cast<int>();
    for (var hour = 0; hour < 24; hour++) {
      expect(hourBranch(hour), expected[hour], reason: 'hour $hour');
    }
    final expectedPeriods = corpus['periods'] as Map<String, dynamic>;
    expect(periods.keys.toSet(), expectedPeriods.keys.toSet());
    for (final entry in expectedPeriods.entries) {
      expect(periods[entry.key], (entry.value as List<dynamic>).cast<int>());
    }
  });

  test('birth context resolves the same intervals, status and candidates', () {
    for (final row in rows(corpus, 'birthContexts')) {
      final profile = row['profile'] as Map<String, dynamic>;
      final birth = birthContext(
        birthDate: profile['birthDate'] as String,
        birthTime: profile['birthTime'] as String?,
        birthCountry: profile['birthCountry'] as String?,
        birthTimezone: profile['birthTimezone'] as String?,
      );
      final label = profile.toString();
      expect(birth.date, row['date'], reason: '$label date');
      expect(birth.clock, row['clock'], reason: '$label clock');
      expect(birth.zones, asStrings(row['zones']), reason: '$label zones');
      expect(birth.zoneSource, row['zoneSource'], reason: '$label zoneSource');
      expect(birth.exact, row['exact'], reason: '$label exact');
      expect(birth.status, row['status'], reason: '$label status');
      expect(
        birth.nonexistentZones,
        asStrings(row['nonexistentZones']),
        reason: '$label nonexistent',
      );
      final expectedIntervals = (row['intervals'] as List<dynamic>)
          .cast<Map<String, dynamic>>();
      expect(
        birth.intervals.length,
        expectedIntervals.length,
        reason: '$label interval count',
      );
      for (var i = 0; i < expectedIntervals.length; i++) {
        expect(
          birth.intervals[i].start,
          asDouble(expectedIntervals[i]['start']),
          reason: '$label interval $i start',
        );
        expect(
          birth.intervals[i].end,
          asDouble(expectedIntervals[i]['end']),
          reason: '$label interval $i end',
        );
        expect(
          birth.intervals[i].zone,
          expectedIntervals[i]['zone'],
          reason: '$label interval $i zone',
        );
      }
    }
  });

  test('civil boundaries match, including zone transitions', () {
    for (final row in rows(corpus, 'civilBoundaries')) {
      expect(
        civilBoundaries(row['date'] as String, row['zone'] as String),
        asDoubles(row['boundaries']),
        reason: '${row['zone']} ${row['date']}',
      );
    }
  });

  test('day segmentation covers 23h and 25h days with no gaps or overlaps', () {
    for (final row in rows(corpus, 'segments')) {
      final zone = row['zone'] as String;
      final ms = asDouble(row['instantMs']);
      final actual = segmentsForDay(ms, zone);
      final expected = (row['segments'] as List<dynamic>)
          .cast<Map<String, dynamic>>();
      final label = '$zone @ ${row['iso']}';
      expect(actual.length, expected.length, reason: '$label segment count');
      for (var i = 0; i < expected.length; i++) {
        expect(
          actual[i].start,
          asDouble(expected[i]['start']),
          reason: '$label $i start',
        );
        expect(
          actual[i].end,
          asDouble(expected[i]['end']),
          reason: '$label $i end',
        );
        expect(
          actual[i].hourBranchIndex,
          expected[i]['hourBranch'],
          reason: '$label $i branch',
        );
        expect(
          actual[i].local.date,
          expected[i]['localDate'],
          reason: '$label $i date',
        );
        expect(
          actual[i].local.clock,
          expected[i]['localClock'],
          reason: '$label $i clock',
        );
        expect(
          actual[i].local.hour,
          expected[i]['localHour'],
          reason: '$label $i hour',
        );
        expect(
          actual[i].local.offsetSeconds,
          asDouble(expected[i]['offsetSeconds']),
          reason: '$label $i offset',
        );
        expect(
          actual[i].local.iso,
          expected[i]['iso'],
          reason: '$label $i iso',
        );
      }

      final expectedPeriods = row['periods'] as Map<String, dynamic>;
      for (final entry in expectedPeriods.entries) {
        final selected = periodSegments(actual, ms, entry.key);
        final want = (entry.value as List<dynamic>)
            .cast<Map<String, dynamic>>();
        expect(
          selected.length,
          want.length,
          reason: '$label ${entry.key} count',
        );
        for (var i = 0; i < want.length; i++) {
          expect(
            selected[i].start,
            asDouble(want[i]['start']),
            reason: '$label ${entry.key} $i start',
          );
          expect(
            selected[i].end,
            asDouble(want[i]['end']),
            reason: '$label ${entry.key} $i end',
          );
          final candidate = want[i]['candidateStart'];
          expect(
            selected[i].candidateStart,
            candidate == null ? null : asDouble(candidate),
            reason: '$label ${entry.key} $i candidateStart',
          );
        }
      }
    }
  });

  test('calendar arithmetic across DST matches moment', () {
    for (final row in rows(corpus, 'addCivil')) {
      final ms = parseInstant(row['iso']);
      expect(
        addCivil(
          ms,
          row['zone'] as String,
          row['years'] as int,
          row['months'] as int,
          row['days'] as int,
          row['hours'] as int,
        ),
        asDouble(row['result']),
        reason:
            '${row['zone']} ${row['iso']} '
            '+${row['years']}y${row['months']}m${row['days']}d${row['hours']}h',
      );
    }
  });

  test('instant parsing accepts and rejects exactly what the engine does', () {
    for (final row in rows(corpus, 'parseInstant')) {
      expect(
        parseInstant(row['value']),
        asDouble(row['ms']),
        reason: '${row['value']}',
      );
    }
    for (final row in rows(corpus, 'parseInstantRejected')) {
      expect(
        () => parseInstant(row['value']),
        throwsA(isA<EngineError>().having((e) => e.code, 'code', row['error'])),
        reason: '${row['value']}',
      );
    }
  });
}
